// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4-kypn0ML-FCJowUwMLf0jCfkZbFi08',
    appId: '1:684880842234:web:e58a8941eddd6fe57da843',
    messagingSenderId: '684880842234',
    projectId: 'demoproject-a3330',
    authDomain: 'demoproject-a3330.firebaseapp.com',
    storageBucket: 'demoproject-a3330.firebasestorage.app',
    measurementId: 'G-LXMH5KFBPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBpGld1FRC4g07N8YwfDYTkv548I5qnM',
    appId: '1:684880842234:android:fcd6c862a48e48677da843',
    messagingSenderId: '684880842234',
    projectId: 'demoproject-a3330',
    storageBucket: 'demoproject-a3330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0H5AnJst_B7shgyiYwGtexyTRFSn2hKU',
    appId: '1:684880842234:ios:8bb0ab21c904da107da843',
    messagingSenderId: '684880842234',
    projectId: 'demoproject-a3330',
    storageBucket: 'demoproject-a3330.firebasestorage.app',
    iosBundleId: 'com.example.newprjoect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0H5AnJst_B7shgyiYwGtexyTRFSn2hKU',
    appId: '1:684880842234:ios:8bb0ab21c904da107da843',
    messagingSenderId: '684880842234',
    projectId: 'demoproject-a3330',
    storageBucket: 'demoproject-a3330.firebasestorage.app',
    iosBundleId: 'com.example.newprjoect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM4-kypn0ML-FCJowUwMLf0jCfkZbFi08',
    appId: '1:684880842234:web:5fea4c8f34621f8a7da843',
    messagingSenderId: '684880842234',
    projectId: 'demoproject-a3330',
    authDomain: 'demoproject-a3330.firebaseapp.com',
    storageBucket: 'demoproject-a3330.firebasestorage.app',
    measurementId: 'G-PLZ9YY1DPF',
  );
}
